services:
  plantmatica-db:
    image: postgres:19beta1-alpine3.23
    container_name: plantmatica-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /data/postgresql:/var/lib/postgresql/19/docker